### ISSUE TITLE
Data Source and License

### ISSUE THREAD

**Issue by CImrie** [georgique/world-geojson#1]
Hey! Fantastic job on this project!

I am building a project where I need specific regions (mainland Spain excluding The Canary Islands for example) and this looks like it might be exactly what I'm after. I just have a few questions:

1. What's the license? Is it MIT?
2. Can you reveal the original data source?
3. How did you produce the split regions? (If there are any missing then I would want to use a similar technique/tools and contribute them back to the repository).

Thanks in advance :)

**Comment by georgique** [comment]
Hey there! Thanks you so much for kind feedback!
1. License is Creative Commons Attribution 4.0 - check it [here](https://github.com/georgique/world-geojson/blob/master/LICENSE)
2. Well, it is all manually made, this is original data source already. 
3. I used geojson.io service and just did everything manually. However, I didn't like that I draw most of borders twice, so lately I started to manually copy past shared border pieces from one region/country to another. But that's tricky, you have to work with raw Geojson. I still haven't developed a nice and effective technique for this. Looking forward to your contribution anyways, and please let me know if you have any questions.
