### ISSUE TITLE
Polygon label and other attributes missing for countries

### ISSUE THREAD

**Issue by WillJonesMapular** [georgique/world-geojson#18]
I am getting countries by name in the countries folder. I think I can get the mainland for each country by getting the first polygon in the feature collection. This is, however, sketchy. An attribute tag like "mainland" would help to differentiate France's mainland from French Guiana for example. Also having labels for these would be great so I could filter to just show French Guiana instead of having to find it in some sketchy way. It would also be nice for labelling these polygons.

**Comment by georgique** [comment]
That's a good idea, but I don't think I have a capacity to do that. Feel free to submit a PR though.
