### ISSUE TITLE
"Czechia" is the official short English name for "The Czech Republic". It is "czech" here. 

### ISSUE THREAD

**Issue by WillJonesMapular** [georgique/world-geojson#19]
Sources:

- https://assets.publishing.service.gov.uk/media/5a8198a1e5274a2e87dbe79f/Czechia_Information_Paper-Updated_September_2016.pdf

- https://mzv.gov.cz/london/en/about_the_czech_republic/basic_information_on_the_czech_republic/index.html

**Comment by georgique** [comment]
Sorry, a bit busy these days. Feel free to submit a pull request with the necessary changes. But if you do, please consider people who already use the old name, it has to have backwards compatibility.

**Comment by georgique** [comment]
Added `czechia.json` in https://github.com/georgique/world-geojson/commit/41f1bc6547215bf2302be6e039f1e8cbce965b81
Will delete `czech.json` in the next major version, keep it now for compatibility.
