### ISSUE TITLE
What is the coordinate system ?

### ISSUE THREAD

**Issue by matcho** [georgique/world-geojson#2]
Hello,
What is the coordinate system you use ? It doesn't look like WGS84…
For example France is supposed to be around lat 45 / lon 3, but the `france.json` file has coordinates around 700 / 50 !?
Thanks for this very useful data.

**Comment by georgique** [comment]
Hi @matcho,
It is WGS84. The reason of your confusion is France's overseas territories. `countries` folder contains information about countries including all their territories. However, if you need mainland only, go to `areas` folder - you'll find it there.

**Comment by matcho** [comment]
Thanks @georgique 
But even in `areas/france/mainland.json`, the first coordinates pair is
```
[
  722.5350952148436,
  51.10007257240614
]
```
I'm confused, because I was expecting latitude to be something between -90 and 90, and longitude between -180 and 180, for any area in the world ?

**Comment by georgique** [comment]
Because these coordinates are decimal representation of latitude and longitude, not pure degrees/minutes/seconds.

**Comment by matcho** [comment]
OK thank you, sorry for the beginner's question :)

**Comment by georgique** [comment]
No problem. :)

**Comment by nitsandaniel** [comment]
@georgique, not sure I understand your answer.
Assuming I have a coordinate in Paris, latitude=48.845483 longitude=2.356652, how can I use your geojson to check if it's part of France?
Is there a way to convert it to the representation you're using?
Thanks!

**Comment by barryrowlingson** [comment]
The longitude values have *not* been mapped to the standard (-180:180) range. In this case:

```
[
  722.5350952148436,
  51.10007257240614
]
```

The 722.535095214843 has gone round the world twice, adding an extra 2*360 degrees, when it would conventionally be: 2.535095214843

Some mapping software will cope with this. Some will not. Github's inline GeoJSON mapper shows it, but you'll see several repeats of the Mercator-projected world.
