### ISSUE TITLE
countries/italy.json raises an error 

### ISSUE THREAD

**Issue by FullFatBart** [georgique/world-geojson#20]
Hi,

I came across an error there. Validator e.g. (https://geojsonlint.com/)  shows:

Line 4163: the first and last positions in a LinearRing of coordinates must be the same
Line 4421: the first and last positions in a LinearRing of coordinates must be the same

I might be able to fix it.

Thanks!

**Comment by georgique** [comment]
@FullFatBart Can you submit a Pull Request for this?

**Comment by FullFatBart** [comment]
Sure, first thing tomorrow morning.

**Comment by georgique** [comment]
Fixed in https://github.com/georgique/world-geojson/commit/41f1bc6547215bf2302be6e039f1e8cbce965b81
Thanks for pointing it out.
