### ISSUE TITLE
Incorrect Russian borders

### ISSUE THREAD

**Issue by DBarinovv** [georgique/world-geojson#21]
According to [github preview](https://github.com/georgique/world-geojson/blob/develop/countries/russia.json), [external sites](https://geojson.io/), and my personal experience, there appears to be an issue with the Russian borders. The current data incorrectly includes parts of Iceland, Greenland, and other regions outside Russia.

![Russia_borders_issue](https://github.com/user-attachments/assets/6cfb6ef3-822b-4c7a-bb92-b1238b32241c)

**Comment by georgique** [comment]
I've seen and investigated these before - unfortunately it seems to be a bug with rendering geojson, not geojson itself. You can even try to reproduce it by findint the point where it gets broken and do a smaller geojson crossing that point - and you should see this bug. 
I don't think there is anything I can do about it.

**Comment by DBarinovv** [comment]
I ran a [test](https://pastebin.com/Evnst5zk), and it returned True for a point in Iceland (-15.883635, 65.373928) being within Russia's borders. This suggests the issue might lie in the data itself, unless I misunderstood something.

**Comment by georgique** [comment]
I am not sure how your test is helpful in this situation.
Just see here, how there is a line where it supposed to connect two points together, and yet it does a whole revolution around the globe to make that connection. That's not the data problem, that's the rendering problem.
![image](https://github.com/user-attachments/assets/9aa171d1-5e29-4979-9445-c5b15c278417)

**Comment by georgique** [comment]
If you find a solution for this, I'll be happy to accept it. But I'm not going to look into it because I already did and I couldn't fix it. I believe it happens only to some of the map engines, doesn't happen in Google Maps for example.

**Comment by DBarinovv** [comment]
Got it, thanks for the explanation. If I manage to find a solution, I’ll let you know. Thanks again!
