### ISSUE TITLE
Coordinates for some countries are incorrect

### ISSUE THREAD

**Issue by dex73** [georgique/world-geojson#5]
Some countries, like Portugal, Ukraine, Lithuania have correct coordinates, that are inside bounds  longitude +/-180, latitude +/-90.

On another side countries like Germany, France, Italy, Georgia etc have coordinates starting from 700... For example this is header of Italy 

```
$ cat ./italy.json | head -n 30
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              727.5311279296875,
              43.77902662160831
            ],
            [
              727.5627136230469,
              43.77456454892858
            ],
            [
              727.5702667236327,
              43.78497553389676
            ],
            [
              727.5984191894531,
              43.781009658142914
            ],
            [
              727.6581573486328,
              43.77109381775651
            ],
```

ER: all coordinates are in  longitude +/-180, latitude +/-90 bounds

**Comment by nomadkj** [comment]
I ran into the same problem.
Is there a fix?

Thanks!

**Comment by georgique** [comment]
Please see https://github.com/georgique/world-geojson/issues/2#issuecomment-494386136
Question is - do you see it as an issue, or is it causing real problems in some software?

**Comment by nomadkj** [comment]
@georgique
As far as I'm aware of, the geojsons with coordinates greater than 180 cannot be used in Leaflet.
It won't show anything, so in that case it's not usable.

It's the best geojson library I could find, so I would really appreciate it if you could look into this!

**Comment by georgique** [comment]
I can look into it, but please try it with Leaflet and provide confirmation that it doesn't work. Otherwise it'd be waste of time.

**Comment by goodwin64** [comment]
Created a PR for this: https://github.com/georgique/world-geojson/pull/6

@dex73 @georgique please take a look when possible.

**Comment by georgique** [comment]
PR merged, issue is fixed

**Comment by georgique** [comment]
PR merged, issue should be gone now.
